name: cytophenograph
channels:
  - conda-forge
  - defaults
dependencies:
  - blas
  - ca-certificates
  - certifi
  - cycler
  - freetype
  - intel-openmp
  - joblib
  - kiwisolver
  - libcxx
  - libcxxabi
  - libedit
  - libffi
  - libgfortran
  - libpng
  - llvm-openmp
  - llvmlite
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - numba
  - openssl
  - opentsne
  - pip
  - pynndescent
  - pyparsing
  - python
  - python-dateutil
  - python_abi
  - pytz
  - readline
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - six
  - sqlite
  - tbb
  - tk
  - tornado
  - umap-learn
  - wheel
  - xz
  - zlib
