# You can use this file to create a conda environment for this pipeline:
# #   conda env create -f environment.yml
 name: cytophenograph2
 channels:
   - conda-forge
   - bioconda
   - defaults
 dependencies:
 ## conda-forge packages
   - conda-forge::python=3.6.1
   - conda-forge::umap-learn
   - conda-forge::openpyxl
 ## bioconda packages
   - bioconda::scanpy
   - pip  
   - pip:
     - leidenalg-0.7.0-cp36-cp36m-win_amd64.whl
     - parc
     - xlrd==1.2.0
     - hnswlib 
