name: Cytophenograph6
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aom=3.5.0
  - appdirs=1.4.4
  - binutils_impl_linux-64=2.39
  - bioconductor-biobase=2.58.0
  - bioconductor-biocgenerics=0.44.0
  - bioconductor-cytolib=2.10.0
  - bioconductor-flowai=1.28.0
  - bioconductor-flowcore=2.10.0
  - bioconductor-rhdf5lib=1.20.0
  - bioconductor-rprotobuflib=2.10.0
  - bioconductor-s4vectors=0.36.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.6.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charls=2.4.1
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorcet=3.0.1
  - contourpy=1.0.7
  - cryptography=39.0.0
  - curl=7.87.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.1.0
  - datashader=0.14.3
  - dav1d=1.0.0
  - et_xmlfile=1.1.0
  - expat=2.5.0
  - fbpca=1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2023.1.0
  - gcc_impl_linux-64=12.2.0
  - geosketch=1.2
  - gettext=0.21.1
  - gfortran_impl_linux-64=12.2.0
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - graphite2=1.3.14
  - gsl=2.7.1
  - gxx_impl_linux-64=12.2.0
  - harfbuzz=6.0.0
  - hnswlib=0.6.2
  - icu=70.1
  - idna=3.4
  - imagecodecs=2022.12.24
  - imageio=2.25.0
  - intervaltree=3.1.0
  - joblib=1.2.0
  - jpeg=9e
  - jxrlib=1.1
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libaec=1.0.6
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.51.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsanitizer=12.2.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=12.2.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=2.32.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.10.3
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - make=4.3
  - matplotlib-base=3.6.3
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=3.0
  - numba=0.56.4
  - numpy=1.23.5
  - openjpeg=2.5.0
  - openpyxl=3.0.10
  - openssl=1.1.1s
  - packaging=23.0
  - pandoc=2.19.2
  - pango=1.50.12
  - param=1.12.3
  - partd=1.3.0
  - pcre2=10.40
  - pip=22.3.1
  - pixman=0.40.0
  - pooch=1.6.0
  - pycparser=2.21
  - pyct=0.4.8
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.16
  - python-annoy=1.17.1
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.7.1
  - pywavelets=1.4.1
  - pyyaml=6.0
  - r-base=4.2.2
  - r-base64enc=0.1_3
  - r-bh=1.81.0_1
  - r-bslib=0.4.2
  - r-cachem=1.0.6
  - r-changepoint=2.2.4
  - r-cli=3.6.0
  - r-colorspace=2.0_3
  - r-cpp11=0.4.3
  - r-crayon=1.5.2
  - r-digest=0.6.31
  - r-ellipsis=0.3.2
  - r-evaluate=0.20
  - r-fansi=1.0.4
  - r-farver=2.1.1
  - r-fastmap=1.1.0
  - r-fs=1.5.2
  - r-ggplot2=3.4.0
  - r-glue=1.6.2
  - r-gtable=0.3.1
  - r-highr=0.10
  - r-htmltools=0.5.4
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.4
  - r-knitr=1.41
  - r-labeling=0.4.2
  - r-lattice=0.20_45
  - r-lifecycle=1.0.3
  - r-magrittr=2.0.3
  - r-mass=7.3_58.1
  - r-matrix=1.5_3
  - r-matrixstats=0.63.0
  - r-memoise=2.0.1
  - r-mgcv=1.8_41
  - r-mime=0.12
  - r-munsell=0.5.0
  - r-nlme=3.1_161
  - r-pillar=1.8.1
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.8
  - r-r6=2.5.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.10
  - r-reshape2=1.4.4
  - r-rlang=1.0.6
  - r-rmarkdown=2.20
  - r-sass=0.4.4
  - r-scales=1.2.1
  - r-stringi=1.7.12
  - r-stringr=1.5.0
  - r-tibble=3.1.8
  - r-tinytex=0.43
  - r-utf8=1.2.2
  - r-vctrs=0.5.1
  - r-viridislite=0.4.1
  - r-withr=2.5.0
  - r-xfun=0.36
  - r-yaml=2.3.6
  - r-zoo=1.8_11
  - readline=8.2
  - requests=2.28.2
  - scanorama=1.7.3
  - scikit-image=0.19.3
  - scikit-learn=1.2.0
  - sed=4.8
  - setuptools=66.1.1
  - six=1.16.0
  - snappy=1.1.9
  - sortedcontainers=2.4.0
  - sqlite=3.40.1
  - sysroot_linux-64=2.12
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tktable=2.10
  - toolz=0.12.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - wheel=0.38.4
  - xarray=2023.1.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxt=1.2.1
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - yaml=0.2.5
  - zfp=1.0.0
  - zlib=1.2.13
  - zlib-ng=2.0.6
  - zstd=1.5.2
  - pip:
    - anndata==0.8.0
    - beautifulsoup4==4.11.1
    - certifi==2022.12.7
    - charset-normalizer==3.0.1
    - datashape==0.5.2
    - decorator==5.1.1
    - deprecated==1.2.13
    - fcsparser==0.2.4
    - fcsy==0.10.0
    - filelock==3.9.0
    - flowcytometrytools==0.5.1
    - future==0.18.3
    - gdown==4.6.0
    - graphtools==1.5.3
    - h5py==3.8.0
    - igraph==0.10.3
    - leidenalg==0.9.1
    - llvmlite==0.39.1
    - minisom==2.3.0
    - multipledispatch==0.6.0
    - natsort==8.2.0
    - pandas==1.3.5
    - patsy==0.5.3
    - phate==1.0.10
    - phenograph==1.5.7
    - pillow==9.4.0
    - progressbar2==4.2.0
    - psutil==5.9.4
    - pybind11==2.10.3
    - pygam==0.8.0
    - pygsp==0.5.1
    - pynndescent==0.5.8
    - python-utils==3.4.5
    - pyvia==0.1.73
    - s-gd2==1.8.1
    - scanpy==1.9.1
    - scipy==1.10.0
    - scprep==1.2.1
    - seaborn==0.12.2
    - session-info==1.0.0
    - soupsieve==2.3.2.post1
    - statsmodels==0.13.5
    - stdlib-list==0.8.0
    - tasklogger==1.2.0
    - termcolor==2.2.0
    - texttable==1.6.7
    - tifffile==2023.1.23.1
    - tqdm==4.64.1
    - umap-learn==0.5.3
    - wget==3.2
    - wrapt==1.14.1
