name: cytophenograph5_1
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alabaster=0.7.12
  - anndata=0.8.0
  - arpack=3.7.0
  - babel=2.9.1
  - backcall=0.2.0
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bioconductor-biobase=2.54.0
  - bioconductor-biocgenerics=0.40.0
  - bioconductor-cytolib=2.6.2
  - bioconductor-flowai=1.24.0
  - bioconductor-flowcore=2.6.0
  - bioconductor-rhdf5lib=1.16.0
  - bioconductor-rprotobuflib=2.6.0
  - bioconductor-s4vectors=0.32.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - colorama=0.4.4
  - cryptography=36.0.2
  - curl=7.83.0
  - cycler=0.11.0
  - debugpy=1.6.0
  - decorator=5.1.1
  - docutils=0.17.1
  - entrypoints=0.4
  - expat=2.4.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=10.3.0
  - gcc_linux-64=10.3.0
  - gettext=0.21.0
  - gfortran_impl_linux-64=10.3.0
  - gfortran_linux-64=10.3.0
  - giflib=5.2.1
  - glpk=4.65
  - gmp=6.2.1
  - graphite2=1.3.14
  - gsl=2.7.1
  - gxx_impl_linux-64=10.3.0
  - gxx_linux-64=10.3.0
  - h5py=3.6.0
  - harfbuzz=4.2.1
  - hdf5=1.12.1
  - icu=70.1
  - idna=3.3
  - imagesize=1.3.0
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - ipykernel=6.13.0
  - ipython=7.33.0
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.1
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.3.1
  - jupyter_core=4.10.0
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=10.3.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libsanitizer=10.3.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=10.3.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.13
  - libzlib=1.2.11
  - llvmlite=0.38.0
  - lz4-c=1.9.3
  - make=4.3
  - markupsafe=2.1.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - metis=5.1.0
  - mpfr=4.1.0
  - munkres=1.1.4
  - natsort=8.1.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.7.1
  - numba=0.55.1
  - numpy=1.21.6
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.3.5
  - pandoc=2.18
  - pango=1.50.7
  - parso=0.8.3
  - patsy=0.5.2
  - pcre=8.45
  - pcre2=10.37
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.1.0
  - pip=22.0.4
  - pixman=0.40.0
  - prompt-toolkit=3.0.29
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.12.0
  - pynndescent=0.5.6
  - pyopenssl=22.0.0
  - pyparsing=3.0.8
  - pysocks=1.7.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2022.1
  - pyzmq=22.3.0
  - r-backports=1.4.1
  - r-base=4.1.3
  - r-base64enc=0.1_3
  - r-bh=1.78.0_0
  - r-brio=1.1.3
  - r-bslib=0.3.1
  - r-callr=3.7.0
  - r-changepoint=2.2.3
  - r-cli=3.3.0
  - r-colorspace=2.0_3
  - r-crayon=1.5.1
  - r-desc=1.4.1
  - r-diffobj=0.3.5
  - r-digest=0.6.29
  - r-ellipsis=0.3.2
  - r-evaluate=0.15
  - r-fansi=1.0.3
  - r-farver=2.1.0
  - r-fastmap=1.1.0
  - r-fs=1.5.2
  - r-getopt=1.20.3
  - r-ggplot2=3.3.6
  - r-glue=1.6.2
  - r-gtable=0.3.0
  - r-highr=0.9
  - r-htmltools=0.5.2
  - r-isoband=0.2.5
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.0
  - r-knitr=1.39
  - r-labeling=0.4.2
  - r-lattice=0.20_45
  - r-lifecycle=1.0.1
  - r-magrittr=2.0.3
  - r-mass=7.3_57
  - r-matrix=1.4_1
  - r-matrixstats=0.62.0
  - r-mgcv=1.8_40
  - r-munsell=0.5.0
  - r-nlme=3.1_157
  - r-optparse=1.7.1
  - r-pillar=1.7.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.4
  - r-plyr=1.8.7
  - r-praise=1.0.0
  - r-processx=3.5.3
  - r-ps=1.7.0
  - r-r6=2.5.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.8.3
  - r-rcpparmadillo=0.11.1.1.0
  - r-rcppparallel=5.1.5
  - r-rematch2=2.1.2
  - r-reshape2=1.4.4
  - r-rlang=1.0.2
  - r-rmarkdown=2.14
  - r-rprojroot=2.0.3
  - r-rstudioapi=0.13
  - r-sass=0.4.1
  - r-scales=1.2.0
  - r-stringi=1.7.6
  - r-stringr=1.4.0
  - r-testthat=3.1.4
  - r-tibble=3.1.7
  - r-tinytex=0.39
  - r-utf8=1.2.2
  - r-vctrs=0.4.1
  - r-viridislite=0.4.0
  - r-waldo=0.4.0
  - r-withr=2.5.0
  - r-xfun=0.31
  - r-yaml=2.3.5
  - r-zoo=1.8_10
  - readline=8.1
  - requests=2.27.1
  - scanpy=1.9.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - sed=4.8
  - session-info=1.0.0
  - setuptools=59.8.0
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sphinx=4.5.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.38.2
  - statsmodels=0.13.2
  - stdlib-list=0.7.0
  - suitesparse=5.10.1
  - sysroot_linux-64=2.12
  - tbb=2021.5.0
  - texttable=1.6.4
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tktable=2.10
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.2.1.post0
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - umap-learn=0.5.3
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xlrd=2.0.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - annoy==1.17.0
    - et-xmlfile==1.1.0
    - fbpca==1.0
    - fcsparser==0.2.4
    - fcsy==0.10.0
    - flowcytometrytools==0.5.1
    - geosketch==1.2
    - hnswlib==0.6.2
    - igraph==0.9.10
    - intervaltree==2.1.0
    - leidenalg==0.8.10
    - minisom==2.3.0
    - openpyxl==3.0.9
    - parc==0.33
    - phenograph==1.5.7
    - pybind11==2.9.2
    - python-igraph==0.9.10
    - scanorama==1.7.1
    - sortedcontainers==2.4.0
